export const CarData = [
  {id: 'dusuhshuf', carType: 'sedan', image: '../Assets/redcar.png'},
  {id: '7gfehueiswhde', carType: 'Hatchback', image: '../Assets/redcar.png'},
  {id: 'gudhswhein', carType: 'MPV', image: '../Assets/redcar.png'},
  {id: 'uygfubiheh', carType: 'SUV', image: '../Assets/redcar.png'},
  {id: 'gfuhbeuue', carType: 'Crossover', image: '../Assets/redcar.png'},
  {id: '7hfue7fh7dg', carType: 'Coupe', image: '../Assets/redcar.png'},
  {id: 'geysudusduhd', carType: 'Convertible', image: '../Assets/redcar.png'},
  {id: 'ttbrr', carType: 'sedan', image: '../Assets/redcar.png'},
  {id: 'uihsu', carType: 'Hatchback', image: '../Assets/redcar.png'},
  {id: 'wege', carType: 'MPV', image: '../Assets/redcar.png'},
  {id: 'rg', carType: 'SUV', image: '../Assets/redcar.png'},
  {id: 'brb', carType: 'Crossover', image: '../Assets/redcar.png'},
  {id: 'dr', carType: ' Coupe', image: '../Assets/redcar.png'},
  {id: 'hj', carType: 'Convertible', image: '../Assets/redcar.png'},
  {id: 'hr4eytjkj', carType: 'Convertible', image: '../Assets/redcar.png'},
];
